// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/amalmadhu06/mariadb-fiber-go/pkg/config"
	"github.com/amalmadhu06/mariadb-fiber-go/pkg/db"
	"github.com/amalmadhu06/mariadb-fiber-go/pkg/http"
	"github.com/amalmadhu06/mariadb-fiber-go/pkg/http/handler"
	"github.com/amalmadhu06/mariadb-fiber-go/pkg/repository"
	"github.com/amalmadhu06/mariadb-fiber-go/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepo := repository.NewUserRepository(gormDB)
	userUsecase := usecase.NewUserUsecase(userRepo)
	userHandler := handler.NewUserHandler(userUsecase)
	serverHTTP := http.NewServerHTTP(userHandler)
	return serverHTTP, nil
}
