// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/amalmadhu06/mariadb-fiber-go/internal/memory"
	"github.com/amalmadhu06/mariadb-fiber-go/internal/repository"
	"github.com/amalmadhu06/mariadb-fiber-go/internal/services"
	"github.com/amalmadhu06/mariadb-fiber-go/internal/web"
	"github.com/amalmadhu06/mariadb-fiber-go/internal/web/handler"
	"github.com/amalmadhu06/mariadb-fiber-go/pkg/config"
	"github.com/amalmadhu06/mariadb-fiber-go/pkg/db"
)

// Injectors from wire.go:

// InjectDependencies takes in configuration values and inject dependencies
// using google wire
func InjectDependencies(cfg config.Config) (*web.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	offerRepo := repository.NewOfferRepository(gormDB)
	offerMemory := memory.NewOfferMemory(offerRepo)
	offerUsecase := services.NewOfferUsecase(offerRepo, offerMemory)
	offerHandler := handler.NewOfferHandler(offerUsecase)
	serverHTTP := web.NewServerHTTP(offerHandler)
	return serverHTTP, nil
}
