// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/amalmadhu06/mariadb-fiber-go/internal/web"
	"github.com/amalmadhu06/mariadb-fiber-go/internal/web/handler"
	"github.com/amalmadhu06/mariadb-fiber-go/internal/repository"
	"github.com/amalmadhu06/mariadb-fiber-go/internal/services"
	"github.com/amalmadhu06/mariadb-fiber-go/pkg/config"
	"github.com/amalmadhu06/mariadb-fiber-go/pkg/db"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*web.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepo := repository.NewUserRepository(gormDB)
	userUsecase := services.NewUserUsecase(userRepo)
	userHandler := handler.NewUserHandler(userUsecase)
	serverHTTP := web.NewServerHTTP(userHandler)
	return serverHTTP, nil
}
