// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/offer.go

// Package mockRepo is a generated GoMock package.
package mockRepo

import (
	context "context"
	reflect "reflect"

	entities "github.com/amalmadhu06/mariadb-fiber-go/internal/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockOfferRepo is a mock of OfferRepo interface.
type MockOfferRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOfferRepoMockRecorder
}

// MockOfferRepoMockRecorder is the mock recorder for MockOfferRepo.
type MockOfferRepoMockRecorder struct {
	mock *MockOfferRepo
}

// NewMockOfferRepo creates a new mock instance.
func NewMockOfferRepo(ctrl *gomock.Controller) *MockOfferRepo {
	mock := &MockOfferRepo{ctrl: ctrl}
	mock.recorder = &MockOfferRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfferRepo) EXPECT() *MockOfferRepoMockRecorder {
	return m.recorder
}

// GetOffer mocks base method.
func (m *MockOfferRepo) GetOffer(ctx context.Context, country string) ([]entities.OfferCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOffer", ctx, country)
	ret0, _ := ret[0].([]entities.OfferCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOffer indicates an expected call of GetOffer.
func (mr *MockOfferRepoMockRecorder) GetOffer(ctx, country interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOffer", reflect.TypeOf((*MockOfferRepo)(nil).GetOffer), ctx, country)
}
